LIB := libreverse.so
INCLUDES :=
LIBS :=

# --------------------------------------------------

CC ?= gcc

# --------------------------------------------------

build:
	$(CC) -shared -fPIC libreverse.c $(INCLUDES) $(LIBS) -o $(LIB)
